name: separate_contaminated_assembly_graphs_env
channels:
  - defaults
  - bioconda
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blast=2.5.0
  - boost=1.84.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - icu=75.1
  - kraken2=2.0.7_beta
  - ld_impl_linux-64=2.40
  - libblas=3.11.0
  - libboost=1.84.0
  - libboost-devel=1.84.0
  - libboost-headers=1.84.0
  - libboost-python=1.84.0
  - libboost-python-devel=1.84.0
  - libcblas=3.11.0
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libidn2=2.3.8
  - liblapack=3.11.0
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lz4-c=1.10.0
  - ncurses=6.5
  - networkx=3.5
  - numpy=2.4.0
  - openssl=3.6.0
  - pcre2=10.45
  - perl=5.26.2
  - pip=25.2
  - popt=1.19
  - pthread-stubs=0.3
  - python=3.13.7
  - python_abi=3.13
  - readline=8.3
  - rsync=3.4.1
  - setuptools=78.1.1
  - sqlite=3.50.2
  - taxonkit=0.20.0
  - tk=8.6.15
  - tzdata=2025b
  - wget=1.25.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xxhash=0.8.3
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
